function PlotTemps(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-Jan-2008 23:13:40

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([3.376e+004 3.553e+004]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([277.8 352.5]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','IATk');
set(plot1(2),'DisplayName','ECTk');
set(plot1(3),'DisplayName','MATk');
set(plot1(4),'DisplayName','TEMPd');
set(plot1(5),'DisplayName','TEMPc');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.4564 0.3014 0.06012 0.1026]);

